version: '3'
networks:
  testNetwork:
    driver: bridge

services:
  postgresql:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
      - POSTGRES_MULTIPLE_DATABASES=WorkoutsDB,GymsDB
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d


  pgBouncer:
    image: bitnami/pgbouncer:latest
    environment:
      - POSTGRESQL_PASSWORD=password
    volumes:
      - ./pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
      - ./userlist.txt:/bitnami/pgbouncer/conf/userlist.txt


  app:
    image: nicknav98/gymplanner:latest
    ports:
      - '5050:5050'

volumes:
  postgres_data:
    driver: local