version: '3'
networks:
  testNetwork:
    driver: bridge

services:
  WorkoutsDB:
    image: bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_USER=admin
      - POSTGRESQL_DATABASE=WorkoutsDB

  GymsDB:
    image: bitnami/postgresql:14
    ports:
      - '5433:5432'
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_USER=admin
      - POSTGRESQL_DATABASE=GymsDB



  pgBouncer:
    image: bitnami/pgbouncer:latest
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_USER=admin
      - POSTGRESQL_HOST=WorkoutsDB
    volumes:
      - ./pgconf:/bitnami/pgbouncer/conf



  app:
    image: nicknav98/gymplanner:latest
    ports:
      - '5050:5050'
