version: '3'
networks:
  testNetwork:
    driver: bridge

services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=WorkoutsDB
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  pgBouncer:
    image: bitnami/pgbouncer:latest

    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=WorkoutsDB
      - POSTGRESQL_HOST=postgres


  app:
    image: nicknav98/gymplanner:latest
    ports:
      - '5050:5050'

volumes:
  postgres_data:
    driver: local